language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install Django
  - pip install django-fontawesome
  - pip install coverage
script:
  - python manage.py test
  - coverage run --source='.' manage.py test
  - coverage report
  - coverage erase
