# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 04:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='UserPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playe_first_name', models.CharField(max_length=20)),
                ('payer_last_name', models.CharField(max_length=20)),
                ('usage', models.CharField(choices=[('HU', 'Heavy Use'), ('MU', 'Moderate Use'), ('LU', 'Light Use'), ('NU', 'Not Using')], default='NU', max_length=2)),
                ('player_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CloudRoni.Team')),
            ],
        ),
    ]
