# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 05:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CloudRoni', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userplayer',
            old_name='payer_last_name',
            new_name='player_first_name',
        ),
        migrations.RenameField(
            model_name='userplayer',
            old_name='playe_first_name',
            new_name='player_last_name',
        ),
    ]
