# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CloudRoni', '0002_auto_20170411_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplayer',
            name='points_scored',
            field=models.IntegerField(default=0),
        ),
    ]
