# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CloudRoni', '0003_userplayer_points_scored'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=200)),
                ('point', models.IntegerField(choices=[(1, '+1'), (-1, '-1'), (5, '+5')], default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CloudRoni.UserPlayer')),
            ],
        ),
    ]
