# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CloudRoni', '0004_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='note',
            field=models.TextField(max_length=200),
        ),
    ]
