# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-18 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CloudRoni', '0007_auto_20171029_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('outcome', models.CharField(choices=[(1, 'Accepted'), (-1, 'Declined'), (0, 'Pending')], max_length=10)),
                ('created_date', models.DateTimeField()),
                ('proposing_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposing_team', to='CloudRoni.Team')),
                ('proposing_team_player_ids', models.ManyToManyField(to='CloudRoni.UserPlayer')),
                ('receiving_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiving_team', to='CloudRoni.Team')),
            ],
        ),
    ]
