# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-23 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CloudRoni', '0008_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='receiving_team_player_ids',
            field=models.ManyToManyField(related_name='receiving_team_player_ids', to='CloudRoni.UserPlayer'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='proposing_team_player_ids',
            field=models.ManyToManyField(related_name='proposing_team_player_ids', to='CloudRoni.UserPlayer'),
        ),
    ]
