# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-25 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CloudRoni', '0010_auto_20180123_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='outcome',
            field=models.CharField(choices=[(1, 'Accepted'), (-1, 'Declined'), (0, 'Pending')], default='Pending', max_length=10),
        ),
    ]
