# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-08 01:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def set_last_league(apps, schema_editor):
    Team = apps.get_model('CloudRoni', 'Team')
    League = apps.get_model('leagues', 'league')
    for team in Team.objects.all():
        league = League.objects.last()
        team.league = league
        team.save()

class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
        ('CloudRoni', '0014_auto_20180129_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leagues.League'),
            preserve_default=False,
        ),
        migrations.RunPython(set_last_league),
    ]
