# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-25 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0006_league_drafted'),
        ('CloudRoni', '0015_team_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplayer',
            name='league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leagues.League'),
            preserve_default=False,
        ),
    ]
