# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-02 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CloudRoni', '0017_auto_20180301_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplayer',
            name='drafted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userplayer',
            name='drafted_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drafted_team', to='CloudRoni.Team'),
        ),
    ]
