# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-13 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
