# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-14 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_league_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='ended',
            field=models.BooleanField(default=False),
        ),
    ]
