# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-15 05:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_auto_20180214_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='thrid',
            new_name='third',
        ),
    ]
