# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-24 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0005_auto_20180215_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='drafted',
            field=models.BooleanField(default=False),
        ),
    ]
