# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-24 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0005_auto_20180215_0526'),
        ('CloudRoni', '0015_team_league'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_date', models.DateTimeField(verbose_name='started')),
                ('end_turn_timer', models.DateTimeField(verbose_name='timer')),
                ('current_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CloudRoni.Team')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.League')),
            ],
        ),
        migrations.CreateModel(
            name='Drafter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drafts.Draft')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.League')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CloudRoni.Team')),
            ],
        ),
    ]
