# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-27 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0004_draft_next_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drafter',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CloudRoni.Team'),
        ),
    ]
